import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search, Star, Sparkles, X} from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
const fallback = 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=900&q=80';
function MovieCard({movie, onClick}) { return <button onClick={()=>onClick(movie.title)} className="group text-left rounded-2xl overflow-hidden bg-white/5 border border-white/10 hover:border-violet-400/60 transition"><img className="h-56 w-full object-cover opacity-80 group-hover:opacity-100" src={movie.poster || fallback} alt=""/><div className="p-4"><p className="font-bold truncate">{movie.title}</p><p className="text-sm text-slate-400 mt-1">{movie.released || 'Unknown year'} · {movie.votes || 0} votes</p></div></button> }
function App(){
 const [movies,setMovies]=useState([]), [query,setQuery]=useState(''), [selected,setSelected]=useState(null), [recommendations,setRecommendations]=useState([]), [loading,setLoading]=useState(true);
 const discover=async(q='')=>{setLoading(true); try {const r=await fetch(`${API}/api/movies?q=${encodeURIComponent(q)}`);setMovies(await r.json())} finally {setLoading(false)}};
 useEffect(()=>{discover()},[]);
 const open=async(title)=>{const [detail,recs]=await Promise.all([fetch(`${API}/api/movies/${encodeURIComponent(title)}`).then(r=>r.json()),fetch(`${API}/api/movies/${encodeURIComponent(title)}/recommendations`).then(r=>r.json())]);setSelected(detail);setRecommendations(recs)};
 return <main className="min-h-screen bg-slate-950 text-slate-100"><header className="max-w-7xl mx-auto px-6 py-6 flex items-center justify-between"><div className="font-black text-2xl tracking-tight">Cine<span className="text-violet-400">Graph</span></div><span className="text-xs text-slate-400 uppercase tracking-widest">Graph-powered discovery</span></header><section className="max-w-7xl mx-auto px-6 py-16"><p className="text-violet-300 font-bold text-sm uppercase tracking-widest">Discover through connections</p><h1 className="text-5xl md:text-7xl font-black max-w-3xl mt-4 leading-tight">Find films through the people and stories you love.</h1><form onSubmit={e=>{e.preventDefault();discover(query)}} className="mt-9 max-w-xl flex bg-white/10 border border-white/10 rounded-2xl p-2"><Search className="m-3 text-violet-300"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a title…" className="bg-transparent outline-none flex-1"/><button className="bg-violet-500 hover:bg-violet-400 px-5 rounded-xl font-bold">Explore</button></form></section><section className="max-w-7xl mx-auto px-6 pb-16"><div className="flex items-center gap-2 mb-6"><Sparkles className="text-violet-400"/><h2 className="text-xl font-bold">Trending in the graph</h2></div>{loading?<p className="text-slate-400">Loading your graph…</p>:<div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">{movies.map(m=><MovieCard key={m.title} movie={m} onClick={open}/>)}</div>}</section>{selected&&<div className="fixed inset-0 z-10 bg-slate-950/90 backdrop-blur overflow-y-auto"><div className="max-w-5xl mx-auto p-6 md:p-12"><button onClick={()=>setSelected(null)} className="float-right p-3 rounded-full bg-white/10"><X/></button><div className="grid md:grid-cols-[280px_1fr] gap-8"><img className="rounded-3xl w-full h-96 object-cover" src={selected.movie.poster||fallback} alt=""/><div><p className="text-violet-300 font-bold uppercase text-xs tracking-widest">{selected.movie.released}</p><h2 className="text-5xl font-black mt-3">{selected.movie.title}</h2><p className="text-slate-300 mt-5 leading-7">{selected.movie.summary||selected.movie.tagline||'No summary available.'}</p><div className="mt-7"><h3 className="font-bold mb-3">Cast & crew</h3><p className="text-slate-400">{selected.people.slice(0,12).map(p=>p.name).join(' · ')}</p></div></div></div><h3 className="text-2xl font-black mt-14 mb-5 flex gap-2"><Star className="text-violet-400"/> Connected picks</h3><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{recommendations.map(m=><MovieCard key={m.title} movie={m} onClick={open}/>)}</div></div></div>}</main>}
createRoot(document.getElementById('root')).render(<App/>);
